### ISSUE TITLE
Setup simulation to Validate Robot Paths Offline

### ISSUE THREAD

**Issue by ShahhhVihaan** [seanres/cram_ros2#4]
Use hardware emulator from ros2_control to simulate robot controllers so that the driver can be launched to test robots offline in the same simulation environment as the online robots.

**Comment by seanres** [comment]
This should be top priority imo to jump start parallel development of features

**Comment by ShahhhVihaan** [comment]
Currently using the instructions on the `ur_robot_driver` [documentation page](https://docs.ros.org/en/ros2_packages/rolling/api/ur_robot_driver/usage.html) to successfully run the robot online but unable to run the robot offline using the `use_mock_hardware` flag while launching the driver.

**Comment by ShahhhVihaan** [comment]
I sought help on a a similar issue on the Universal Robots ROS2 Driver github and the response did not help.
https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/823#issuecomment-1925933382

**Comment by ShahhhVihaan** [comment]
After comparing the `ur_description` and `ur_moveit_config` packages I found out some version discrepancies and fixed them. The `use_fake_hardware` flag now works.
